INSERT INTO Department VALUES ('CS', 'Computer Science');
INSERT INTO Department VALUES ('IS', 'Information Systems');
INSERT INTO Department VALUES ('MATH', 'Mathematics');
INSERT INTO Department VALUES ('STAT', 'Statistics');
INSERT INTO Department VALUES ('ENG', 'English');
INSERT INTO Department VALUES ('GERM', 'German');
INSERT INTO Department VALUES ('ENGR', 'Engineering');
INSERT INTO Department VALUES ('BUS', 'Business');
INSERT INTO Department VALUES ('EDU', 'Education');
INSERT INTO Department VALUES ('ECON', 'Economics');
INSERT INTO Department VALUES ('SPAN', 'Spanish');
INSERT INTO Department VALUES ('ART', 'Art');
INSERT INTO Department VALUES ('BIO', 'Biology');
INSERT INTO Department VALUES ('CHEM', 'Chemistry');
INSERT INTO Department VALUES ('GEOG', 'Geography');
INSERT INTO Department VALUES ('GEOL', 'Geology');

INSERT INTO Professor VALUES (1, 'Branden','Nelson', 'CS');
INSERT INTO Professor VALUES (2, 'Echo','Welch', 'IS');
INSERT INTO Professor VALUES (3, 'Henry','Bell', 'MATH');
INSERT INTO Professor VALUES (4, 'Luke','Calhoun', 'STAT');
INSERT INTO Professor VALUES (5, 'Hedley','Valentine', 'ENG');
INSERT INTO Professor VALUES (6, 'Darrel','Herman', 'GERM');
INSERT INTO Professor VALUES (7, 'Chelsea','Villarreal', 'ENGR');
INSERT INTO Professor VALUES (8, 'Steel','Espinoza', 'BUS');
INSERT INTO Professor VALUES (9, 'Latifah','Dale', 'EDU');
INSERT INTO Professor VALUES (10, 'Rigel','Arnold', 'ECON');
INSERT INTO Professor VALUES (11, 'Zelenia','Webb', 'SPAN');
INSERT INTO Professor VALUES (12, 'Kalia','Gallegos', 'ART');
INSERT INTO Professor VALUES (13, 'Rashad','Blake', 'BIO');
INSERT INTO Professor VALUES (14, 'Sybil','Haney', 'CHEM');
INSERT INTO Professor VALUES (15, 'Clayton','Holman', 'GEOG');
INSERT INTO Professor VALUES (16, 'Leilani','Gilliam', 'GEOL');
INSERT INTO Professor VALUES (17, 'Bertha','Cherry', 'CS');
INSERT INTO Professor VALUES (18, 'Blair','King', 'ECON');
INSERT INTO Professor VALUES (19, 'Elijah','Hendricks', 'CHEM');
INSERT INTO Professor VALUES (20, 'Brynn','Rivera', 'GEOL');
INSERT INTO Professor VALUES (21, 'Regan','Hart', 'SPAN');

INSERT INTO Program VALUES (1,'CS',333,21,'S','Azerbaijan','Trier',2254.56,'ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec',25);
INSERT INTO Program VALUES (2,'IS',126,12,'S','Barbados','Christchurch',225.45,'tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus',24);
INSERT INTO Program VALUES (4,'ENGR',264,17,'S','Tunisia','Bionaz',4154.56,'eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum',21);
INSERT INTO Program VALUES (5,'SPAN',274,18,'S','Guatemala','Sluis',354.56,'lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus',24);
INSERT INTO Program VALUES (6,'GEOG',148,1,'S','Bahamas','Flamierge',1254.56,'lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam',23);
INSERT INTO Program VALUES (7,'CHEM',244,16,'F','Germany','Whitewater Region Township',2254.99,'in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non',28);
INSERT INTO Program VALUES (8,'SPAN',172,6,'F','Sierra Leone','San Lorenzo',2345.21,'aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum',26);
INSERT INTO Program VALUES (9,'GEOG',124,4,'F','Slovakia','Grand-RosiŽre-Hottomont',2654.46,'dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque',34);
INSERT INTO Program VALUES (10,'STAT',290,14,'F','Reunion','Reno',2134.60,'ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin',23);
INSERT INTO Program VALUES (11,'IS',192,8,'F','Guam','Charleroi',1254.96,'dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget',23);
INSERT INTO Program VALUES (12,'CS',161,4,'F','Latvia','Perth',321.56,'tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus.',33);
INSERT INTO Program VALUES (14,'ECON',135,9,'F','Japan','Saint-Remy-Geest',454.96,'volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus',37);
INSERT INTO Program VALUES (15,'SPAN',252,18,'F','Rwanda','Greenock',1287.66,'commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede.',31);
INSERT INTO Program VALUES (16,'CS',338,18,'I','Lithuania','Kawawachikamach',478.85,'ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor',40);
INSERT INTO Program VALUES (17,'GEOL',110,11,'I','Turkey','Kelowna',2897.36,'vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque',39);
INSERT INTO Program VALUES (18,'GEOL',223,13,'I','French Polynesia','Erode',224.61,'a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',35);
INSERT INTO Program VALUES (19,'GEOG',236,15,'I','Russian Federation','Harrisburg',987.36,'metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget',38);
INSERT INTO Program VALUES (21,'STAT',126,17,'I','Central African Republic','Santa Marina',2254.56,'tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse',26);
INSERT INTO Program VALUES (22,'SPAN',384,3,'I','Jersey','Buzenol',453.56,'congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum',33);
INSERT INTO Program VALUES (23,'GEOL',149,20,'I','Djibouti','Villa Alemana',147.32,'tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula',40);
INSERT INTO Program VALUES (24,'IS',129,5,'I','Burkina Faso','Gulfport',1144.56,'eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut',32);
